[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = { eth-sepolia = "${SEPOLIA_RPC_URL}", arb-sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}", zksync = "https://sepolia.era.zksync.dev"}


remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@ccip/contracts=lib/chainlink-local/lib/ccip/contracts",
    "@chainlink-local=lib/chainlink-local",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
